turismo/Controllers/AdministrarRolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Collections;
using turismo.ViewModel.AdministrarRol;

namespace turismo.Controllers
{
    public class AdministrarRolController : Controller
    {
        
        //
        // GET: /AdministrarRol/
        public turismo_uvmEntities db;
       
        public ActionResult panelAdministrativo()
        {   
            //(en constructor)
            db = new turismo_uvmEntities();
            //los view
            ViewBag.roles = db.rol.ToList();
            ViewBag.programas = db.programa.ToList();
            ViewBag.personas = db.persona.ToList();
            ViewBag.suscripciones = db.suscripcion.ToList();
            return View();
        }

    }
}

turismo/Controllers/EmailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using turismo.Helpers;


namespace turismo.Controllers
{
    public class EmailController : Controller
    {
        //
        // GET: /Email/

        public ActionResult enviarCorreo()
        {

           EmailFactory factory = new EmailFactory();

           factory.agregarDestinatario("ghostdisk@hotmail.cl");
           factory.agregarDestinatario("csaldiasrussell@gmail.com");
           //factory.agregarDestinatario("pedrocarrasco@gmail.com");
           factory.enviarCorreo("Turismo uvm","Este correo esta enviado desde la paguina web www.turismouvm.cl y se mamaran este corre cada vez que cargue la paguina Saludos wetas");
            return View();
        }

    }
}

turismo/Controllers/InicioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using turismo.ViewModel.Registro;


namespace turismo.Controllers
{
    public class InicioController : Controller
    {
        //
        // GET: /Inicio/
        public turismo_uvmEntities db;
        public InicioController() {

            db = new turismo_uvmEntities();

        }
        
        public ActionResult Portada()
        {
         
            //ViewBag.personas = db.persona.ToList();
            return View();
        }

        public ActionResult Plantilla()
        {
            return View();
        }
    }
}

turismo/Controllers/MailersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mvc.Mailer;
using turismo.Mailers;
namespace turismo.Controllers
{
    public class MailersController : Controller
    {
        //
        // GET: /Mailers/
        private IUserMailer _userMailer = new UserMailer();
        public IUserMailer UserMailer
        {
            get { return _userMailer; }
            set { _userMailer = value; }
        }
        public ActionResult Index()
        {
            UserMailer.Welcome().Send();
            return View();
        }

    }
}

turismo/Controllers/PerfilController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace turismo.Controllers
{
    public class PerfilController : Controller
    {
        //
        // GET: /Perfil/

        public ActionResult Perfil()
        {
            return View();
        }

    }
}

turismo/Controllers/PerfilUsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace turismo.Controllers
{
    public class PerfilUsuarioController : Controller
    {
        //
        // GET: /PerfilUsuario/

        public ActionResult Perfil()
        {
            return View();
        }

    }
}

turismo/Controllers/RegistroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using turismo.ViewModel.Registro;
using turismo.Helpers;
using turismo.Mailers;
using Mvc.Mailer;
using System.Diagnostics;

namespace turismo.Controllers
{
    public class RegistroController : Controller
    {
        private IUserMailer _userMailer = new UserMailer();
        public IUserMailer UserMailer
        {
            get { return _userMailer; }
            set { _userMailer = value; }
        }
        public turismo_uvmEntities db;
        

        public ActionResult nuevoRegistro()
        {
            RegistroViewModel nuevo = new RegistroViewModel();

            return View(nuevo);
        }
        [HttpPost]
        public ActionResult nuevoRegistro(RegistroViewModel input) {
         
            try{
            
            if (ModelState.IsValid)
            {
                    persona p = new persona();
                    p.email = input.email;
                    p.password = input.contraseña;
                    p.rol_id = 3;
                    p.nombre_usuario = "anonimus";
                    p.token = Guid.NewGuid().ToString();
                    ViewBag.linkUrl = "?token=" + p.token;
                    //VIewBag.urlLink = System.Web.HttpContext.Current.Request.Url.GetLeftPart(UriPartial.Authority) + "/Account/ConfirmAccount?token=" + token;
                    
                    MvcMailMessage mail = UserMailer.CorreoConfirmacion(p);
                    mail.Send();
                    //(en constructor)
                    db = new turismo_uvmEntities();
                    //luego para guardar
                    db.persona.Add(p);
                    db.SaveChanges();

                    return RedirectToAction("Terminos", new { Id = p.id });
                }
              }
                catch (Exception e) {
                    ModelState.AddModelError("email",e.Message);
                }
                
            return View(input);
        }

        //**===================================================================================================*/


        public ActionResult Terminos( int id)
        {

           
           return View();
        }

        //**===================================================================================================*/
        //[AllowAnonymous]
        //[HttpGet]
        public ActionResult confirmacionCorreo()
        {
            
            return View();
        }
        public ActionResult correoConfirmacion()
        {

            return View();
        }
        public ActionResult recuperarContraseña()
        {
            return View();
        }
        public ActionResult envioRecuperarContraseña()
        {
            return View();
        }
        

        public string email { get; set; }

        public string token { get; set; }
    }
}

turismo/Controllers/ViajesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace turismo.Controllers
{
    public class ViajesController : Controller
    {
        //
        // GET: /Viajes/
        public ActionResult Categoria()
        {
            return View();
        }
        public ActionResult listaViajes()
        {
            return View();
        }
        public ActionResult caracteristicas()
        {
            return View();
        }
        
        public ActionResult lugar()
        {
            return View();
        }
        public ActionResult AmericaLatina()
        {
            return View();
        }
    }
}

turismo/Controllers/pruebaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace turismo.Controllers
{
    public class pruebaController : Controller
    {
        //
        // GET: /prueba/

        public ActionResult Index()
        {
            return View();
        }

    }
}

turismo/Views/Inicio/Portada.cshtml
@{
    ViewBag.Title = "Portada";
}
 
<div class="estilo">
<script type="text/javascript">
    jQuery(document).ready(function () {
        //código a ejecutar cuando el DOM está listo para recibir instrucciones.
        setInterval("cambiarImg()", 5000);
    });
    function cambiarImg() {
        var fotos = Array();
        fotos[0] = "1.jpg";
        fotos[1] = "2.jpg";
        fotos[2] = "3.jpg";
        fotos[3] = "4.jpg";
        random = Math.floor(Math.random() * fotos.length);
        foto_actual = fotos[random];
        url = 'http://@HttpContext.Current.Request.Url.Authority';
        console.log(url);
        console.log("foto = " + foto_actual);
        $(".featured").css("background-image", "url(" + url + "/Content/assets/img/baner/" + foto_actual + ")");
    }
</script>

<div class="featured" >
    <div class="featured-content">
        <h1>Busca gente cerca de ti para viajar</h1>
        <br />
        <h4>Conoce el mundo y a otros como tú!</h4>
    </div>
</div>


<div id="col1" class="">
    <h2>Iniciar sesión</h2>
      <input placeholder="john.doe@example.net" />
      <br />
     <input placeholder="Contraseña" />
     <br />
    <div class="btn-group">
      @Html.ActionLink("Olvido su contraseña", "recuperarContraseña", "Registro", 
                 null, new { @class = "btn  btn-inverse", style = "margin-left:10px;" })
      @Html.ActionLink("Entrar", "categoria", "Viajes", null, new { @class = "btn btn-inverse", style = "margin-left:10px;" })
    </div>
</div>
<div id="col2" >
    <h2>¿Eres nuevo?</h2>
    <table>
        <tr>
            <td>Entra como Visita o registrate en 3 sencillos pasos</td>
        </tr>
        <tr style="text-align:center;">
            
            <td>@Html.ActionLink("Visitas", "Categoria", "Viajes", 
                 null, new { @class = "btn btn-large btn-inverse", style = "margin-left:10px;" })
                 @Html.ActionLink("Registrarse", "nuevoRegistro", "Registro", 
                 null, new { @class = "btn btn-large btn-inverse", style = "margin-left:10px;" })
            </td>
        </tr>
    </table>
</div>


<style>
   body {
        
        background-attachment: fixed;
        background-image: url("Content/assets/img/fondos/fondo_registro.jpg");
        background-position: top center;
        background-repeat: no-repeat;
 
        margin:0;
        padding: 0;
 
        background-size: cover;
        -moz-background-size: cover;
        -webkit-background-size: cover;
}
 
/*
This next definition doesn't allow the background to get any smaller
than a predefined size (640x426px in this case). Change the values
here to match your background image size. The configuration in the
flexi-background javascript file should also match these values.
*/
 
@@media only all and (max-width: 640px) and (max-height: 426px) {
body {
background-size: 640px 426px;
-moz-background-size: 640px 426px;
-webkit-background-size: 640px 426px;
}
}
 
/*
The next 2 definitions are for support in iOS devices.
Since they don't recoginze the 'cover' keyword for background-size
we need to simulate it with percentages and orientation
*/
 
@@media only screen and (orientation: portrait) and (device-width: 320px), (device-width: 768px) {
body {
-webkit-background-size: auto 100%;
}
}
 
@@media only screen and (orientation: landscape) and (device-width: 320px), (device-width: 768px) {
body {
-webkit-background-size: 100% auto;
}
}
    center {
        color:#fcf000; text-shadow: 0 0 0.2em #000, 0 0 0.2em #000,
               0 0 0.2em #000
        
 
        
    }
    .well {
        color:#000;
        text-shadow:none;
        height:250px;
        word-break:keep-all;
        overflow-x:hidden;
        overflow-y: auto;
        text-align:left;
    }
    .estilo {
        color:#fff;
        margin:-30px 0px;
    }
    .featured {
        text-shadow: 0 0 0.3em #bab5b5, 0 0 0.3em #bab5b5, 0 0 0.3em #bab5b5;
    }
    #col1 {
        text-shadow: 0 0 0.3em #000, 0 0 0.3em #000, 0 0 0.3em #000;
    }
    #col2 {
        text-shadow: 0 0 0.3em #000, 0 0 0.3em #000, 0 0 0.3em #000;
    }
    .link {
         text-shadow:none;
    }
</style>
</div>

turismo/Views/Perfil/Perfil.cshtml
@{
    ViewBag.Title = "Perfil";
}
<style>
   body {
        
        background-attachment: fixed;
        background-color: #333;
        background-image: url(/Content/assets/img/fondos/fondo_perfil.jpg);
        background-position: top center;
        background-repeat: no-repeat;
 
        margin:0;
        padding: 0;
 
        background-size: cover;
        -moz-background-size: cover;
        -webkit-background-size: cover;
}
 
/*
This next definition doesn't allow the background to get any smaller
than a predefined size (640x426px in this case). Change the values
here to match your background image size. The configuration in the
flexi-background javascript file should also match these values.
*/
 
@@media only all and (max-width: 640px) and (max-height: 426px) {
body {
background-size: 640px 426px;
-moz-background-size: 640px 426px;
-webkit-background-size: 640px 426px;
}
}
 
/*
The next 2 definitions are for support in iOS devices.
Since they don't recoginze the 'cover' keyword for background-size
we need to simulate it with percentages and orientation
*/
 
@@media only screen and (orientation: portrait) and (device-width: 320px), (device-width: 768px) {
body {
-webkit-background-size: auto 100%;
}
}
 
@@media only screen and (orientation: landscape) and (device-width: 320px), (device-width: 768px) {
body {
-webkit-background-size: 100% auto;
}
}
    center {
        color:#fff; text-shadow: 0 0 0.2em #000, 0 0 0.2em #000,
               0 0 0.2em #000;
        text-align:left;
      
 
        
    }
    .well {
        color:#000;
        text-shadow:none;
        height:250px;
        word-break:keep-all;
        overflow-x:hidden;
        overflow-y: auto;
        text-align:left;
    }
    h3 {
        text-align:left;
    }
</style>
<center><h2>Perfil</h2></center>

<div>
    <div></div>
    






</div>

turismo/Views/Shared/Menu.cshtml
<!-- navbar -->
	<div id="topnav" class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				
				<!-- .btn-navbar is used as the toggle for collapsed navbar content -->
				<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</a>
      
				<!-- Collapse - Everything you want hidden at 940px or less, place within here -->
      			<div class="nav-collapse">
					<!-- Main nav -->
					<ul  class="nav">
						<li class="active">@Html.ActionLink("Inicio","Portada","Inicio")</li>
                                            <!--(nombre, metodo, controlador) -->
						<li>@Html.ActionLink("Ver plantilla","Plantilla","Inicio")</li>
						<li>@Html.ActionLink("Mi Perfil","Perfil","Perfil")</li>
                        <li>@Html.ActionLink("Categoria de viajes","Categoria","Viajes")</li>
                        <li>@Html.ActionLink("Cerrar sesión","","")</li>
                        <li>@Html.ActionLink("Panel Administrativo","panelAdministrativo","AdministrarRol")</li>

						<li><a href="#contact-section">Contacto</a></li>
					</ul><!-- ENDS main nav -->
				
			
				
				</div><!-- ENDS Collapse -->
				
			</div>
		</div>
	</div><!-- ENDS navbar -->

turismo/Views/registro/Terminos.cshtml
@{
    ViewBag.Title = "Terminos";
}
@ViewBag.ids
<style>
    body {
        background-attachment: fixed;
        background-color: #333;
        background-image: url(/Content/assets/img/fondos/fondo_registro.jpg);
        background-position: top center;
        background-repeat: no-repeat;
        margin: 0;
        padding: 0;
        background-size: cover;
        -moz-background-size: cover;
        -webkit-background-size: cover;
    }

    /*
This next definition doesn't allow the background to get any smaller
than a predefined size (640x426px in this case). Change the values
here to match your background image size. The configuration in the
flexi-background javascript file should also match these values.
*/

    @@media only all and (max-width: 640px) and (max-height: 426px) {
        body {
            background-size: 640px 426px;
            -moz-background-size: 640px 426px;
            -webkit-background-size: 640px 426px;
        }
    }

    /*
The next 2 definitions are for support in iOS devices.
Since they don't recoginze the 'cover' keyword for background-size
we need to simulate it with percentages and orientation
*/

    @@media only screen and (orientation: portrait) and (device-width: 320px), (device-width: 768px) {
        body {
            -webkit-background-size: auto 100%;
        }
    }

    @@media only screen and (orientation: landscape) and (device-width: 320px), (device-width: 768px) {
        body {
            -webkit-background-size: 100% auto;
        }
    }

    center {
        color: #fff;
        text-shadow: 0 0 0.2em #000, 0 0 0.2em #000, 0 0 0.2em #000;
    }

    .well {
        color: #000;
        text-shadow: none;
        height: 250px;
        font-size: 11pt;
    }

    .toc {
        height: 225px;
        width: 100%;
        word-break: keep-all;
        overflow-x: hidden;
        overflow-y: auto;
        text-align: left;
        font-family: "Courier New", Courier, monospace;
    }

    .long-question {
        width: 100%;
        height: 25px;
        margin: 0;
        color: #fff;
        padding: 3px;
        text-shadow: none;
        text-align: center;
        background: rgb(243,197,189); /* Old browsers */
        background: -moz-linear-gradient(top, rgba(243,197,189,1) 0%, rgba(232,108,87,1) 50%, rgba(234,40,3,1) 51%, rgba(255,102,0,1) 75%, rgba(199,34,0,1) 100%); /* FF3.6+ */
        background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(243,197,189,1)), color-stop(50%,rgba(232,108,87,1)), color-stop(51%,rgba(234,40,3,1)), color-stop(75%,rgba(255,102,0,1)), color-stop(100%,rgba(199,34,0,1))); /* Chrome,Safari4+ */
        background: -webkit-linear-gradient(top, rgba(243,197,189,1) 0%,rgba(232,108,87,1) 50%,rgba(234,40,3,1) 51%,rgba(255,102,0,1) 75%,rgba(199,34,0,1) 100%); /* Chrome10+,Safari5.1+ */
        background: -o-linear-gradient(top, rgba(243,197,189,1) 0%,rgba(232,108,87,1) 50%,rgba(234,40,3,1) 51%,rgba(255,102,0,1) 75%,rgba(199,34,0,1) 100%); /* Opera 11.10+ */
        background: -ms-linear-gradient(top, rgba(243,197,189,1) 0%,rgba(232,108,87,1) 50%,rgba(234,40,3,1) 51%,rgba(255,102,0,1) 75%,rgba(199,34,0,1) 100%); /* IE10+ */
        background: linear-gradient(to bottom, rgba(243,197,189,1) 0%,rgba(232,108,87,1) 50%,rgba(234,40,3,1) 51%,rgba(255,102,0,1) 75%,rgba(199,34,0,1) 100%); /* W3C */
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f3c5bd', endColorstr='#c72200',GradientType=0 ); /* IE6-9 */
    }
</style>
@using (Html.BeginForm("ConfirmacionCorreo","Registro"))
{
    <center>
    <h2>Terminos y Condiciones</h2>
    <div class="well">
        <div class="toc">
            Prohibición de uso con fines ilícitos o prohibidos: Usted acepta que no usará los Sitios web ni los Materiales con fines ilícitos o prohibidos por estos Términos y condiciones de uso. Usted no puede:
            <ol>
            <li>cargar, publicar, enviar mensajes de correo electrónico, transmitir o de otro modo proporcionar contenido ilícito, nocivo, amenazante, abusivo, hostil, ultrajante, difamatorio, vulgar, obsceno, injurioso, que invada la privacidad de un tercero, que promueva el odio o la xenofobia o que de otra manera sea inaceptable;</li>
            <li>utilizar los Sitios web, Materiales, servicios o actividades para "asediar" o de otra manera acosar o molestar a otra persona;</li>
            <li>hacerse pasar por una persona física o jurídica, como por ejemplo un funcionario de Intel, el coordinador de un foro, un guía o anfitrión, realizar declaraciones falsas o de otro modo erróneas de su vinculación con una persona física o jurídica o recopilar o almacenar datos personales de otros usuarios en relación con la conducta y las actividades prohibidas;</li>
            <li>falsificar encabezados o manipular identificadores de otro modo a fin de ocultar el origen de los contenidos transmitidos por los Sitios web o Materiales;</li>
            <li>cargar, publicar, enviar por correo electrónico, transmitir o proporcionar de otro modo cualquier contenido respecto del cual no tenga derecho a transmitir en virtud de la ley o de relaciones contractuales o de confianza (por ejemplo, información privilegiada, información registrada y confidencial obtenida o revelada en ocasión de relaciones laborales o protegida por convenios de no divulgación);</li>
            <li>cargar, publicar, enviar por correo electrónico, transmitir o proporcionar de otro modo cualquier contenido que infrinja derechos de patente, marca comercial, secreto comercial, derechos de autor u otros derechos de propiedad intelectual (los "Derechos") de cualquier parte;</li>
            <li>cargar, publicar, enviar por correo electrónico, transmitir o proporcionar de otro modo anuncios publicitarios no solicitados o no autorizados, material promocional, "correo basura", "correo no solicitado", "cartas en cadena", "esquemas de pirámide" o cualquier otro tipo de oferta no solicitada;</li>
            <li>cargar, publicar, enviar por correo electrónico, transmitir o proporcionar de otro modo materiales que contengan virus informáticos o cualquier otro código informático, archivos o programas diseñados para interrumpir, destruir o limitar la funcionalidad del software, hardware o de equipos de telecomunicaciones;</li>
            <li>no podrá utilizar el Sitio web ni los Materiales de una manera que pudiera dañar, deshabilitar, recargar o alterar los servidores de Intel o las conexiones de redes, ignorar requisitos, procedimientos, políticas o normas de redes conectadas al Sitio web o los Materiales o que pudieran interferir con el uso y goce de los Sitios web o Materiales por parte de cualquier tercero;</li>
            <li>no podrá tratar de obtener acceso no autorizado a los Sitios web o Materiales, otras cuentas, sistemas informáticos o redes conectadas a los servidores, a través de ataques propios de piratas informáticos, el descifrado de contraseñas o cualquier otro método ni obtener ni tratar de obtener materiales o información con cualquier medio que no se ofrece intencionalmente a través de los Sitios web o Materiales;</li>
            <li>infringir de manera intencional o no las leyes locales, estatales, nacionales o internacionales aplicables.</li>
            </ol>
        </div>
        <div class="long-question">
            
          <script>
              $("form").submit(function () {
                  var seleccionado = $(".ck").is(":checked");
                  if (seleccionado == true) {
                      return true;
                  }
                  else {
                      alert("acepte las condiciones de uso");
                      return false;
                  }
                      
              });
           </script>
                <input type="checkbox"  class="ck"/>

            Acepto las condiciones de uso.
        </div>
    </div>    
    <input type="submit" value="Continuar" class="btn btn-large btn-inverse" style = "margin-left:10px;" />
</center>
}

turismo/Views/registro/confirmacionCorreo.cshtml
@{
    ViewBag.Title = "confirmacionCorreo";
   
}


<style>
   body {
        
        background-attachment: fixed;
        background-color: #333;
        background-image: url(/Content/assets/img/fondos/fondo_registro.jpg);
        background-position: top center;
        background-repeat: no-repeat;
 
        margin:0;
        padding: 0;
 
        background-size: cover;
        -moz-background-size: cover;
        -webkit-background-size: cover;
}
 
/*
This next definition doesn't allow the background to get any smaller
than a predefined size (640x426px in this case). Change the values
here to match your background image size. The configuration in the
flexi-background javascript file should also match these values.
*/
 
@@media only all and (max-width: 640px) and (max-height: 426px) {
body {
background-size: 640px 426px;
-moz-background-size: 640px 426px;
-webkit-background-size: 640px 426px;
}
}
 
/*
The next 2 definitions are for support in iOS devices.
Since they don't recoginze the 'cover' keyword for background-size
we need to simulate it with percentages and orientation
*/
 
@@media only screen and (orientation: portrait) and (device-width: 320px), (device-width: 768px) {
body {
-webkit-background-size: auto 100%;
}
}
 
@@media only screen and (orientation: landscape) and (device-width: 320px), (device-width: 768px) {
body {
-webkit-background-size: 100% auto;
}
}
    center {
        color:#fff; text-shadow: 0 0 0.2em #000, 0 0 0.2em #000,
               0 0 0.2em #000;
        text-align:left;
      
 
        
    }
    .well {
        color:#000;
        text-shadow:none;
        height:250px;
        word-break:keep-all;
        overflow-x:hidden;
        overflow-y: auto;
        text-align:left;
    }
    h3 {
        text-align:left;
    }
</style>
<center>
    <br />
        <h2>Confirmación Correo</h2>

        Un email a sido enviado a @ViewBag.personas, con el que podrás activar tu cuenta
        <br />
    <br />
    <br />
    <br />
    
      @Html.ActionLink("Volver inicio", "Portada", "Inicio", null, new { @class = "btn btn-large btn-inverse", style = "margin-left:10px;" })

     @ViewBag.confirmacion
</center>

turismo/Views/registro/correoConfirmacion.cshtml
@{
    ViewBag.Title = "correoConfirmacion";
}

<h2>correoConfirmacion</h2>

turismo/Views/registro/envioRecuperarContraseña.cshtml
@{
    ViewBag.Title = "envioRecuperarContraseña";
}
<style>
   body {
        
        background-attachment: fixed;
        background-color: #333;
        background-image: url(/Content/assets/img/fondos/fondo_registro2.jpg);
        background-position: top center;
        background-repeat: no-repeat;
 
        margin:0;
        padding: 0;
 
        background-size: cover;
        -moz-background-size: cover;
        -webkit-background-size: cover;
}
 
/*
This next definition doesn't allow the background to get any smaller
than a predefined size (640x426px in this case). Change the values
here to match your background image size. The configuration in the
flexi-background javascript file should also match these values.
*/
 
@@media only all and (max-width: 640px) and (max-height: 426px) {
body {
background-size: 640px 426px;
-moz-background-size: 640px 426px;
-webkit-background-size: 640px 426px;
}
}
 
/*
The next 2 definitions are for support in iOS devices.
Since they don't recoginze the 'cover' keyword for background-size
we need to simulate it with percentages and orientation
*/
 
@@media only screen and (orientation: portrait) and (device-width: 320px), (device-width: 768px) {
body {
-webkit-background-size: auto 100%;
}
}
 
@@media only screen and (orientation: landscape) and (device-width: 320px), (device-width: 768px) {
body {
-webkit-background-size: 100% auto;
}
}
    center {
        color:#fff; text-shadow: 0 0 0.2em #000, 0 0 0.2em #000,
               0 0 0.2em #000;
        text-align:left;
      
 
        
    }
    .well {
        color:#000;
        text-shadow:none;
        height:250px;
        word-break:keep-all;
        overflow-x:hidden;
        overflow-y: auto;
        text-align:left;
    }
    h3 {
        text-align:left;
    }
</style>
<center>
    <br />
        <h2> Recuperación de Contraseña</h2><br />

       La contraseña fue enviada a su correo exitosamente. 
        <br />
    <br />
    <br />
    <br />
    
      @Html.ActionLink("Volver inicio", "Portada", "Inicio", null, new { @class = "btn btn-large btn-inverse", style = "margin-left:10px;" })
</center>

turismo/Views/registro/recuperarContraseña.cshtml
@{
    ViewBag.Title = "recuperarContraseña";
}
<style>
   body {
        
        background-attachment: fixed;
        background-color: #333;
        background-image: url(/Content/assets/img/fondos/fondo_registro2.jpg);
        background-position: top center;
        background-repeat: no-repeat;
 
        margin:0;
        padding: 0;
 
        background-size: cover;
        -moz-background-size: cover;
        -webkit-background-size: cover;
}
 
/*
This next definition doesn't allow the background to get any smaller
than a predefined size (640x426px in this case). Change the values
here to match your background image size. The configuration in the
flexi-background javascript file should also match these values.
*/
 
@@media only all and (max-width: 640px) and (max-height: 426px) {
body {
background-size: 640px 426px;
-moz-background-size: 640px 426px;
-webkit-background-size: 640px 426px;
}
}
 
/*
The next 2 definitions are for support in iOS devices.
Since they don't recoginze the 'cover' keyword for background-size
we need to simulate it with percentages and orientation
*/
 
@@media only screen and (orientation: portrait) and (device-width: 320px), (device-width: 768px) {
body {
-webkit-background-size: auto 100%;
}
}
 
@@media only screen and (orientation: landscape) and (device-width: 320px), (device-width: 768px) {
body {
-webkit-background-size: 100% auto;
}
}
    center {
        color:#fff; text-shadow: 0 0 0.2em #000, 0 0 0.2em #000,
               0 0 0.2em #000
 
        
    }
</style>
<center>

    <h1>Recuperar Contraseña</h1>
    <br />
    <h3>ingrese sus datos:</h3>
    <br />
                 <input name="" placeholder="Correo electronico" /> <br />
                 
                 
                 @Html.ActionLink("Recuperar contraseña", "envioRecuperarContraseña", "Registro", 
                 null, new { @class = "btn btn-large btn-inverse", style = "margin-left:10px;" })
</center>